// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktrwishjtcdmdwkvyhis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cndpc2hqdGNkbWR3a3Z5aGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDE5NDIsImV4cCI6MjA2MTAxNzk0Mn0.dWnyKQzUE4YF4X6eXbnPGcr3QRLrbnJ6bTXbwErik_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);